language: cpp
compiler:
  - gcc
  - clang
cache:
  directories:
  - mpich
before_install:
  - sh ./get_mpich.sh
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../minimizer
  - make -j
  - cd ./bin/
  - ./test_minimizer --gtest_list_tests
notifications:
  email: false
