language: cpp
install:
  - sudo apt-get install libcr-dev mpich mpich-doc
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake -D USE_MPI=ON ../minimizer
  - make -j
  - cd ./bin/
  - ./test_minimizer --gtest_list_tests
notifications:
  email: false
