language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../minimizer
  - make -j
  - cd ./bin/
  - ./test_minimizer --gtest_list_tests
notifications:
  email: false
