language: cpp
install:
  - sudo apt-get install mpich libmpich-dev
compiler:
  - gcc
  - clang
script:
- mkdir ../build
- cd ../build
- cmake ../minimizer
- make -j
- cd ./bin/
- ./sample dims=2 epsPar=0.001 rPar=4.0 Nmax=100000000 epsErr=0.01
notifications:
  email: false
