language: cpp
install:
  - sudo apt-get install libcr-dev mpich mpich-doc
compiler:
  - gcc
  - clang
script:
mkdir build
- cd build
- cmake -D USE_MPI=ON CMAKE_BUILD_TYPE=RELEASE ..
- cmake --build . --config -j4
- cd ./bin/
- ./test_minimizer --gtest_list_tests
notifications:
  email: false
