language: cpp
install:
  - sudo apt-get install mpich libmpich-dev
compiler:
  - gcc
  - clang
script:
- mkdir ../build
- cd ../build
- cmake ../minimizer
- make -j
- cd ./bin/
- ./test_minimizer_seq --gtest_list_tests
- ./test_minimizer_AGMND --gtest_list_tests
- ./test_minimizer_AGP_D --gtest_list_tests
- mpirun -np 2 ./test_minimizer_par --gtest_list_tests
- mpirun -np 5 ./test_minimizer_par --gtest_list_tests
- mpirun -np 9 ./test_minimizer_par --gtest_list_tests
notifications:
  email: false
